### ISSUE TITLE
Organización del texto

### ISSUE THREAD

**Issue by aeromero2** [Practicum42-MP-20201/tarea1-ensayo-de-analisis-JeanM1996#1]
Sugiero que piense en dos cosas:

- Comentarios de la película
- Aportes  de su trabajo en circunstancias expuestas.

Al final de la primera, debe haber una frase que empate con la segunda idea.

**Comment by JeanM1996** [comment]
Se ha añadido el comentario y opinión sobre la pelicula, y ademas se ha seguido consejos a la retroalimentación propuesta
